language: python
python:
  - 2.7
  - pypy

before install:
 - sudo apt-get update
 - sudo apt-get install python-setuptools

script:
 - cd BinPy/tests/
 - nosetests -v gates_tests.py
 - nosetests -v ics_tests.py